FROM autostructure/puppet_ubuntu

<% if maintainer %>MAINTAINER <%= maintainer %><% end %>

<% if image_user && !image_user.empty? %>USER root<% end %>

<% if modules %>
<% modules.each do |name, value| %>
RUN puppet module install <%= name %>
<% end %>
<% end %>

<% if rocker %>MOUNT /opt/puppetlabs /etc/puppetlabs /root/.gem<% end %>

<% if labels && !labels.empty? %>LABEL <%= labels.map { |g| g.split('=') }.map { |k,v| "#{k}=\"#{v}\"" }.join(' ') %><% end %>

<% if apt_proxy %>ARG APT_PROXY<% end %>

<% if use_factfile %>
    COPY <%= factfile %> /etc/puppetlabs/facter/facts.d/custom_facts.txt
<% end %>

<% if module_path && !master %>
COPY <%= module_path %> /etc/puppetlabs/code/modules/
<% end %>

<% if manifest && !master %>
COPY <%= File.dirname(manifest) %> /<%= File.dirname(manifest) %>
<% end %>

<% if use_hiera && !master %>
COPY <%= hiera_config %> /hiera.yaml
COPY <%= hiera_data %> /hieradata
<% end %>

<% if autosign_token %>ARG AUTOSIGN_TOKEN<% end %>

<% if os %>
  <% if master %>
    <% if os == 'ubuntu' or os == 'debian' %>
RUN <% if apt_proxy %>echo "Acquire::HTTP::Proxy \"$APT_PROXY\";" >> /etc/apt/apt.conf.d/01proxy && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy && <% end %>apt-get update && \
<% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose <% if puppet_debug %>--debug <% end %>--onetime --no-daemonize <% if show_diff %>--show_diff <% end %>--summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* <% if apt_proxy %>&& rm -f /etc/apt/apt.conf.d/01proxy<% end %>
    <% elsif os == 'centos' %>
RUN yum update -y && \
    <% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose <% if puppet_debug %>--debug <% end %>--onetime --no-daemonize <% if show_diff %>--show_diff <% end %>--summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    yum clean all
    <% elsif os == 'alpine' %>
RUN apk update && \
    <% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose <% if puppet_debug %>--debug <% end %>--onetime --no-daemonize <% if show_diff %>--show_diff <% end %>--summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    rm -rf /var/cache/apk/*
    <% end %>
  <% else %>
    <% if os == 'ubuntu' or os == 'debian' %>
RUN <% if apt_proxy %>echo "Acquire::HTTP::Proxy \"$APT_PROXY\";" >> /etc/apt/apt.conf.d/01proxy && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy && <% end %>apt-get update && \
    FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --detailed-exitcodes --verbose <% if puppet_debug %>--debug <% end %><% if show_diff %>--show_diff <% end %>--summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management ; \
    rc=$?; if [ $rc -ne 0 ] && [ $rc -ne 2 ]; then exit 1; fi && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* <% if apt_proxy %>&& rm -f /etc/apt/apt.conf.d/01proxy<% end %>
    <% elsif os == 'centos' %>
RUN yum update -y && \
    FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --verbose <% if puppet_debug %>--debug <% end %><% if show_diff %>--show_diff <% end %>--summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management && \
    yum clean all
    <% elsif os == 'alpine' %>
RUN apk update && \
    FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --verbose <% if puppet_debug %>--debug <% end %><% if show_diff %>--show_diff <% end %>--summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management && \
    rm -rf /var/cache/apk/*
    <% end %>
  <% end %>
<% end %>

<% if expose && !expose.empty? %>EXPOSE <%= expose.join(' ') %><% end %>
<% if volume && !volume.empty? %>VOLUME <%= volume.join(' ') %><% end %>

<% if entrypoint && !entrypoint.empty? %>ENTRYPOINT <%= entrypoint.to_s %><% end %>
<% if cmd && !cmd.empty? %>CMD <%= cmd.to_s %><% end %>

<% if image_user && !image_user.empty? %>USER <%= image_user.to_s %><% end %>

<% if rocker %>TAG <%= image_name %><% end %>
